timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
title: MatchMaker Style Template
domain: mmstyle.dicax.org
layout: default
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .vs/
defaults:
sass:
  style: expanded
